package model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import java.util.*

class AppDataInfo(
    @DynamoDBHashKey(attributeName = "id")
    var id: String,

    var model: String? = null,

    var version: String? = null,

    var environment: String? = null,

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    var updatedAt: Date? = null
) {


    constructor() : this("", "", null, null, null)

    companion object {
        val MOBILE_VERSIONING_TABLE = System.getenv("MOBILE_VERSIONING_TABLE")
        const val ID = "id"
        const val ENVIRONMENT = "environment"
        const val MODEL = "model"
        const val VERSION = "version"
    }
}