package model

import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.util.*

@DynamoDBTable(tableName = "appDataInfo")
data class AppDataInfo(
//    @DynamoDBHashKey(attributeName = "id")
//    var id: String,

    @get:DynamoDBAttribute
    var so: String? = null,

    @get:DynamoDBAttribute
    var version: String? = null,

    @get:DynamoDBAttribute
    var environment: String? = null,

    @get:DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    var updatedAt: Date? = null
) {


    constructor() : this("", null, null, null)

    constructor(so: String, appVersion: String, environment: String?) : this(so, appVersion, environment, null)

    companion object {
        val MOBILE_VERSIONING_TABLE = System.getenv("MOBILE_VERSIONING_TABLE")
        const val ID = "id"
        const val ENVIRONMENT = "environment"
        const val VERSION = "version"
        const val SO = "so"
    }

    private var id: String? = null

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    fun getId(): String? {
        return id
    }

    fun setId(id: String) {
        this.id = id
    }

}

